// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function ListNodes(arg1, arg2) {
  return window['go']['main']['App']['ListNodes'](arg1, arg2);
}
