// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentContext():Promise<string>;

export function ListNodes(arg1:boolean,arg2:string):Promise<main.QueriedNodes>;
