// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {k8s} from '../models';

export function GetCurrentContext():Promise<string>;

export function ListNodes(arg1:boolean):Promise<Array<k8s.Node>>;
